homeassistant:
  name: Looniversity
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  temperature_unit: C
  unit_system: metric
  time_zone: Europe/London

  customize: !include customize.yaml

zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:briefcase


input_slider: !include input_slider.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml

group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
script: !include scripts.yaml
automation: !include automation.yaml

#conversation:
discovery:
frontend:
history:
logbook:
sun:
updater:


#device_tracker:
#  platform: nmap_tracker
#  hosts: 192.168.0.1/24
#  home_interval: 10
#  track_new_devices: yes


#device_tracker owntracks:
#  platform: owntracks


media_player:
  - platform: cast
  - platform: plex


http:
  api_password: !secret api_key_homeassistant

recorder:
  db_url: !secret postgresql_connection
  exclude:
    domains:
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

mqtt:
  broker: !secret mqtt_host
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant


influxdb:
  host: !secret influxdb_host
#  username: homeassistant
#  password: !secret influxdb_password

light:
  platform: hue
  host: !secret hue_host
  allow_unreachable: true

zwave:
  usb_path: /zwavestick-usb

rfxtrx:
  device: /rfxtrx-usb

#logger:
#  default: warning
#  logs:
#    homeassistant.components.device_tracker.mqtt: debug
