- platform: mqtt
  state_topic: "owntracks/dhdzsvay/nexus6p"
  name: "Nexus 6P Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt|int }}'

- platform: mqtt
  state_topic: "device/pixelc/battery"
  name: "Pixel C Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.level }}'

- platform: mqtt
  state_topic: "device/nexus7/battery"
  name: "Nexus 7 Battery Level"
  unit_of_measurement: "%"
  value_template: '{{ value_json.level }}'

# forecast.io
- platform: forecast
  api_key: 31d8eec0008aeb35289f652e0705e4d7
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - cloud_cover
    #- precip_type
    #- precip_intensity
    #- precip_probability
    #- wind_speed
    #- wind_bearing
    #- humidity
    #- pressure

- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ states("input_slider.alarm_hour") }}:{% if states("input_slider.alarm_minute")|length == 1 %}0{% endif %}{{ states("input_slider.alarm_minute") }}'

    mediaplayeroff_time:
      friendly_name: 'Time'
      value_template: '{{ states("input_slider.mediaplayeroff_hour") }}:{% if states("input_slider.mediaplayeroff_minute")|length == 1 %}0{% endif %}{{ states("input_slider.mediaplayeroff_minute") }}'

