title: Load of Junk
views:
  - title: Home
    icon: mdi:home-outline
    cards:
      - type: custom:weather-card
        entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: entities
            title: Sunrise / Sunset
            show_header_toggle: false
            entities:
              - sensor.nextsunrise
              - sensor.nextsunset

  - title: Lights
    icon: mdi:lightbulb-outline
    cards:
      - type: entities
        title: Lounge
        show_header_toggle: false
        entities:
          - light.lounge_lamp_1
          - light.lounge_lamp_2

      - type: entities
        title: Entrance
        show_header_toggle: false
        entities:
          - light.hall

      - type: entities
        title: Landing
        show_header_toggle: false
        entities:
          - light.landing

      - type: entities
        title: Study
        show_header_toggle: false
        entities:
          - light.desk
          - light.study_ceiling
          - switch.cabinet
          - switch.under_desk

  - title: Media
    icon: mdi:file-music-outline
    cards:
      - type: custom:mini-media-player
        entity: media_player.lounge_2
        artwork: cover
      - type: custom:mini-media-player
        entity: media_player.lounge
        artwork: full-cover-fit
      - type: custom:mini-media-player
        entity: media_player.kitchen
        artwork: cover
      - type: custom:mini-media-player
        entity: media_player.bedroom_home
        artwork: cover

  - title: Status
    icon: mdi:comment-question-outline
    cards:
      - type: entities
        show_header_toggle: false
        title: Loft
        entities:
          - entity: sensor.loft_temp
            name: Temperature
          - entity: sensor.loft_humidity
            name: Humidity
      - type: entities
        show_header_toggle: false
        title: Node 0
        entities:
          - entity: sensor.node0_temp
            name: Temperature
          - entity: sensor.node0_humidity
            name: Humidity

      - type: entities
        show_header_toggle: false
        title: Main Bedroom
        entities:
          - entity: sensor.main_bedroom_temp
            name: Temperature
          - entity: sensor.main_bedroom_humidity
            name: Humidity

      - type: entities
        entities:
          - entity: input_boolean.night_mode
          - entity: input_boolean.away_mode

resources:
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module

  - url: /community_plugin/weather-card/weather-card.js
    type: module

  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module

