version: '3'
volumes:
  grafana:

services:
  tsdb:
    container_name: influxdb
    image: influxdb:latest
    network_mode: "host"
    ports:
      - "8086:8086"
    volumes:
      - /srv/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /srv/influxdb:/var/lib/influxdb

  tsdb_ui:
    container_name: chronograf
    image: quay.io/influxdb/chronograf:latest
    network_mode: "host"
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: http://127.0.0.1:8086
    depends_on:
      - "tsdb"

  aggregator:
    container_name: telegraf
    image: telegraf:latest
    network_mode: "host"
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"


  graphing:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - "tsdb"

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    network_mode: "host"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
        - /srv/mosquitto/config:/mosquitto/config
        - /srv/mosquitto/data:/mosquitto/data
        - /srv/mosquitto/log:/mosquitto/log

  db:
    container_name: postgres
    image: postgres:latest
    network_mode: "host"
    ports:
      - "5432:5432"
    env_file:
      - ".docker-env"
    volumes:
        - /srv/postgresql:/var/lib/postgresql

  samba:
    image: dperson/samba
    network_mode: "host"
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /srv/samba:/etc/samba

