version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: always
    network_mode: "host"
    volumes:
      - /var/lib/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      # - /etc/letsencrypt:/etc/letsencrypt
    devices:
      - "/dev/serial/by-id/usb-RFXCOM_RFXtrx433_06VTMY2H-if00-port0:/rfxtrx-usb"
      - "/dev/serial/by-id/usb-0658_0200-if00:/zwavestick-usb"

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: always
    network_mode: "host"
    volumes:
      - /var/lib/appdaemon/config:/conf
      - /etc/localtime:/etc/localtime:ro
      # - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "5050:5050"
    expose:
      - "5000"
