- alias: Stop The Music
  trigger:
    platform: state
    entity_id: input_boolean.mediaplayeroff_enable
    to: 'on'
    for:
      hours: '{{ int(states.input_slider.mediaplayeroff_hour.state) }}'
      minutes: '{{ int(states.input_slider.mediaplayeroff_minute.state) }}'
  action:
    - service: media_player.turn_off
      data_template:
        entity_id: >
          {% if states("input_select.mediaplayeroff_mediaplayer") == "All" %}
            - media_player.main_bedroom
            - media_player.shield
            - media_player.kitchen
          {% elif states("input_select.mediaplayeroff_mediaplayer") == "Bedroom" %}
            media_player.main_bedroom
          {% elif states("input_select.mediaplayeroff_mediaplayer") == "Lounge" %}
            media_player.shield
          {% elif states("input_select.mediaplayeroff_mediaplayer") == "Kitchen" %}
            media_player.kitchen
          {% endif %}
    - service: input_boolean.turn_off
      entity_id: input_boolean.mediaplayeroff_enable

- alias: 'Wake Me Up'
  trigger:
    platform: template
    value_template: '{{ now.time().strftime("%-H") == states("input_slider.alarm_hour") and now.time().strftime("%-M") == states("input_slider.alarm_minute") }}'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_status
          state: 'on'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
  action:
    service: light.turn_on
    entity_id: light.bed_side_light
